name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/update_readme.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "omarbasem.0101@gmail.com"
          git config --global user.name "OmarBasem"
          git diff
          git commit -am "Update README with latest star counts" || echo "No changes to commit"
          git push
